apiVersion: v1
entries:
  db:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-06-03T10:48:51.406958268Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: a0fc3ba9731a9c30fc18f6e464fdc3cd1c44776b50015a9b51d2a9926431a88a
    home: huwelijksplanner.online
    icon: huwelijksplanner.online
    name: db
    urls:
    - db-0.1.0.tgz
    version: 0.1.0
generated: "2020-06-03T10:48:51.398592072Z"
