apiVersion: v1
entries:
  db:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-06-09T16:39:47.976884329Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: c11ff2726b6816ae81446dedba617f4a80633c811758d98116a6a23e002026ba
    home: huwelijksplanner.online
    icon: huwelijksplanner.online
    name: db
    urls:
    - db-0.1.0.tgz
    version: 0.1.0
generated: "2020-06-09T16:39:47.973593036Z"
